version: '3.8'

services:
  app:
    container_name: ezloc
    build:
      context: .
      args:
        SEO_TITLE: "EzLoc"
        SEO_DESCRIPTION: "EzLoc"
        SEO_URL: "https://example.com/"
        SEO_IMAGE: ""
        SEO_FAVICON: ""
        SEO_PRICE_RANGE: ""
        SEO_PHONE: ""
        SEO_LAT: ""
        SEO_LNG: ""
        SEO_ADDRESS_STREET: ""
        SEO_ADDRESS_ZIP: ""
        SEO_ADDRESS_LOCALITY: ""
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data
      #- ./index.html:/pb_public/index.html (uncomment to override (SEO injection will be skipped))
      - ./css:/pb_public/css
      - ./js:/pb_public/js
      - ./pb_hooks:/pb_hooks
      - ./pb_migrations:/pb_migrations
    restart: unless-stopped
